# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "base58"
pin "wallet_provider"
pin "solana_utils"
pin "solana_errors"
pin "solana_stores"
pin "phantom_deeplink"
pin "cosign"
pin "turf_board"
pin "slate_simulator"
pin "contest_lock_picker"
pin "image_dropzone"
pin "card_list_filter"
