# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "debug_logger"
pin "base58"
pin "wallet_provider"
pin "solana_utils"
pin "solana_errors"
pin "solana_stores"
pin "phantom_deeplink"
pin "cosign"
pin "lock_contest"
pin "turf_board"
pin "slate_simulator"
pin "contest_lock_picker"
pin "card_list_filter"
pin "entry_token_badge"
pin "username_rename_form"
pin "seeds_bar"
pin "state_fanout"
